### ISSUE TITLE
README contains disparaging FUD about other projects

### ISSUE THREAD

**Issue by jmarshall** [umccr/htsget-rs#117]
From _README.md_:

> This implementation gets rid of the [`unsafe` interfacing](https://github.com/rust-bio/rust-htslib) with the C-based [htslib](https://github.com/samtools/htslib), which has had [many vulnerabilities](https://github.com/samtools/htslib/pulls?q=oss-fuzz) along with other [problematic third party dependencies such as OpenSSL](https://www.openssl.org/news/vulnerabilities.html).

There are four real CVEs listed for HTSlib. The last non-trivial one of those was fixed two years and seven releases ago.

Your “many vulnerabilities” link is to a list of HTSlib PRs derived from OSS-Fuzz reports, many of which will likely have been short-lived problems in code on the **develop** branch that were never present in an HTSlib release. Moreover, would you prefer to use a C library that is not being constantly fuzz-tested and does not have such issues identified and fixed?

As the author of this README text has previously been informed, HTSlib itself does not directly use OpenSSL. Only its S3 support (in _hfile_s3*.c_) — which can be built separately as a plugin if desired, thus isolating the dependency — will use OpenSSL as one option for providing the cryptographic routines it needs. If you prefer an HTSlib built without that dependency at all, it is simple to configure your HTSlib build accordingly.

So this text serves no purpose for your users, is largely incorrect or misleading, and casts unwarranted aspersions at HTSlib and its authors — several of whom, incidentally, are involved with htsget.

This text does not reflect well on your project.

**Comment by brainstorm** [comment]
> As the author of this README text has previously been informed, HTSlib itself does not directly use OpenSSL

John, you are being [aggressive as usual... who's disparaging?](https://twitter.com/jomarnz/status/1568212651297079297).

<img width="632" alt="Screen Shot 2022-09-10 at 8 55 50 am" src="https://user-images.githubusercontent.com/175587/189456257-0ec1dd41-5d1c-452b-b1f7-83ee832e6997.png">

It does directly use/link against OpenSSL if the intended use is Amazon's S3, which is our particular usecase, not HPC nor local. I know [cloud-native functionality is not a priority right now for htslib](https://github.com/samtools/htslib/issues?q=is%3Aopen+is%3Aissue+label%3AS3), but it is for us. So that leads to many vulnerabilities (for us, at least). I don't "prefer" I must link against OpenSSL, so that justifies the README comment.

But let's imagine we don't use S3 for a moment, what do you think about [this recent zlib CVE](https://www.cve.org/CVERecord?id=CVE-2022-37434)? That's a recent and [required htslib dependency](https://github.com/samtools/htslib/blob/f307dfbf5c7723956e788e0bdab269fe3d626b83/INSTALL#L36) that has a 9.8 critical base score (out of 10).

The unsafe remarks on the README refer to the inherent undefined behaviour and security issues that C has, it's not ideological, [it's factual](https://msrc-blog.microsoft.com/2019/07/22/why-rust-for-safe-systems-programming/), Rust's compiler safety guarantees rule out a lot of bugs (and potential exploits). I don't have any problem with fuzzing and static analysis, but sooner or later you'll have those bugs cropping up in what can be used as critical/medical software anyway.

I think that lashing out here like you do with many other OSS projects (and people) elsewhere does not reflect well on yourself.

**Comment by jmarshall** [comment]
Thank you for pointing out that HTSlib's S3 support is important for this project.

You may wish to audit the four OpenSSL functions used in _hfile_s3*.c_ (`EVP_sha1()`, `EVP_sha256()`, `SHA256()`, and `HMAC()`) with a view to identifying the actual attack surface exposed: the S3 code uses only a small fraction of OpenSSL's code. HTSlib can use OpenSSL or CommonCrypto to provide this functionality; you may be interested in revisiting previous unmerged work to enable it to use GnuTLS or NSS instead, or in suggesting another source of similar functions easily usable from C that you think has a better security story — perhaps NaCl or something similar but more recent?

Anyway, OpenSSL is not really the issue here. The issue is that the text is or is perceived to be:

* inaccurate (e.g. the categorisation as “many vulnerabilities” and the implication that OpenSSL is a required HTSlib dependency, as you don't state “required for the S3 support needed by htsget-rs” or similar)
* disparaging to other projects — mostly HTSlib but also OpenSSL

I am sure you agree that statements made about other projects should be accurate and factual. I would hope you can see that avoiding (even the appearance of) disparaging other projects in your landing page README is a no-brainer right thing to do. IMHO the htsget-rs maintainers should discuss amongst themselves what their goals here are: even if you do not believe yourself that the statements are inaccurate or disparaging, perhaps the maintainers can see how other people can reasonably read them as such and therefore that htsget-rs would be improved by rewording or removing this text to avoid this possibility.

Re zlib's CVE-2022-37434, HTSlib does not use `inflateGetHeader()` so is unaffected by this issue. If you prefer, you can configure HTSlib to use libdeflate to mostly avoid use of zlib's `inflate()` too.

I understand that `unsafe` is a technical term in Rust, and I did not take issue with that part of the problematic text. Removing the remainder of the quoted sentence after the comma would remove the inaccuracy and disparagement against HTSlib, while maintaining the purely factual ideological point about avoiding C libraries:

> This implementation gets rid of the [`unsafe` interfacing](https://github.com/rust-bio/rust-htslib) with the C-based [HTSlib](https://github.com/samtools/htslib).

That part of the sentence contains the point that you are making for your users. The rest is immaterial to your users and inaccurate and disparaging to other projects, and removing it would resolve this issue. I suggest the htsget-rs maintainers discuss what their goals are with this paragraph and consider editing it as suggested.

(This project was recently presented to the htsget meeting by @mmalenic, during which this problematic text was apparent on screen.)

I suggest you also discuss with your colleagues whether unsubstantiated personal accusations such as “aggressive as usual” and “lashing out” are appropriate.

**Comment by jkbonfield** [comment]
HTSlib is probably one of the most strenuously tested Bioinformatics projects out there, thanks to both Google's OSS-Fuzz team and of course our own Samtools team which also take bugs and particularly security seriously.  The fact that bugs have been found is inevitable, but they get fixed promptly.  Yes there may be bugs reported in some of the libraries we use too, but if the fuzzing system isn't working out how to exploit them then almost certainly that'll be because we're not using that particular bit of the library (which is usually the case).  So I do consider the tarring of "unsafe" and "many vulnerabilities" as over the top and pretty much just mud slinging.  Thank you though for updating the README; you're not just appeasing John.

Finally, I know Rust is a considerably tighter language for such things, but I wouldn't necessarily assume that the other libraries you depend on are any more secure nor that there aren't some accidental issues with unsafe parts of Rust, not unless you equally have as much fuzzing infrastructure around to test the edge cases too.

**Comment by ohofmann** [comment]
@jmarshall @jkbonfield Thank you for pointing out the issues above. We'll have a discussion here and review the htsget-rs documentation to ensure a more neutral tone.

**Comment by mmalenic** [comment]
Thanks for the feedback @jmarshall @jkbonfield. It was not my intention to present disparaging text during the htsget meeting. As @ohofmann said, we'll review the documentation and fix the issues.

**Comment by brainstorm** [comment]
@jmarshall, apologies for characterising you as “aggressive” in response to your comment on Twitter about not being able to take me seriously as a colleague. What I meant to say was that your feedback **felt** aggressive to me and made me feel uncomfortable, a reaction other contributors to similar open-source projects have voiced previously. I have edited my original comment above accordingly and would appreciate it if, in response, you could remove your Twitter comment.
