### ISSUE TITLE
Convert Storage and HtsGet traits to use async/await

### ISSUE THREAD

**Issue by chris-zen** [umccr/htsget-rs#16]
For the current MVP, having blocking operations is fine. But for real life we should convert those interfaces to use async/await.

I think that this is something we can leave for later when we have the basic parts of the search logic well figured out, and possibly more relevant before we start working on the HTTP layer.

```rust
#[async_trait(?Send)]
pub trait Storage {
  async fn get<K: AsRef<str>>(&self, key: K, options: GetOptions) -> Result<PathBuf>;
  async fn url<K: AsRef<str>>(&self, key: K, options: UrlOptions) -> Result<Url>;
}
```

```rust
#[async_trait(?Send)]
pub trait HtsGet {
  async fn search(&self, query: Query) -> Result<Response>;
}
```

**Comment by brainstorm** [comment]
Tangentially related with https://github.com/zaeleus/noodles/issues/9 and https://github.com/umccr/s3-rust-noodles-bam (other related dependencies that are async already for this project).

**Comment by brainstorm** [comment]
After a short chat with @mmalenic, he is very keen to tackle this task. Due to my previous (bad) experience with Rusoto and async (quite a few months ago), I warned Marko that it can get tricky in a jiffy, depending on library maturity (that's why it's labeled as "advanced"). 

One of main concerns I have is the whole red/blue functions debate when implementing mixes between async and blocking, namely:

https://blainehansen.me/post/red-blue-functions-are-actually-good/ 

So, having said that, @zaeleus, do you have plans to start an async branch for Noodles anytime soon? Do you anticipate any major blockers with Noodles if we start with this task?

/cc @CastilloDel

**Comment by zaeleus** [comment]
I just recently started the noodles [`async` branch](https://github.com/zaeleus/noodles/tree/async), so it's still very early to use. BAM and BGZF do have readers, which can be enabled using the `async` feature.

Note that async noodles only supports [Tokio](https://tokio.rs/).

**Comment by brainstorm** [comment]
@chris-zen Any reason why you proposed the interface to be `#[async_trait(?Send)]` instead of just implementing it with Send by default?
